<?php

//Skeleton name
define("NESYS_SKELETON", "Barney");

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';
//Load Nesys CMS Framework core
require __DIR__ . "/../libs/Nesys/NesysCore.php";

ini_set('session.gc_maxlifetime',120960009045);


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
$configurator->setDebugMode(\Nesys\NesysCore::isDebugMode());
$configurator->enableDebugger(__DIR__ . '/../log');
Nette\Diagnostics\Debugger::$strictMode = FALSE;



// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->addDirectory(__DIR__ . '/../app')
	->register();

$configurator = \Nesys\NesysCore::init($configurator);



// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
if ($_SERVER["REMOTE_ADDR"] == "127.0.0.1"){
    $configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section
}

$container = $configurator->createContainer();



//$container->session->setSavePath(__DIR__."/sessions");

//$container->addService("lol", new \Nesys\Articles($container->nette->database->default,$container->nesys->core));
$container->application->onStartup[] = function() use ($container,$configurator) {
/* 
 * Dynamické nahrání a vytvoření služeb 
 * VAROVÁNÍ! Nefunguje injectování pomocí inject<service>();
 */

//dump($container->articles->getArticle(7)->nadpis);
/////////////////////////////////////////////////////////////
};

return $container;
