<?php

header('HTTP/1.1 503 Service Unavailable');
header('Retry-After: 300'); // 5 minutes in seconds

?>
<!DOCTYPE html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name=robots content=noindex>
	<meta name=generator content='Nette Framework'>
	<title>Songátor je vypnut</title>
	<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
	<style>
		body {
			font-family: sans-serif;
		}
	</style>
</head>
<body>
	<div class="container jumbotron">
		<h1>Songátor je vypnut</h1>

		<p>Portál je z důvodu údržby systému vypnutý. Vraťte se sem prosím později</p>
	</div>
</body>
<?php

exit;
